export const animeListData = [
  {
    index: 1,
    releaseYear: "2013",
    name: "Attack On Titan",
    genre: "Action, Dark fantasy, Post-apocalyptic",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt2560140/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/levi_ackerman.jpg",
  },
  {
    index: 2,
    releaseYear: "2019",
    name: "Demon Slayer",
    genre: "Adventure Dark fantasy Martial arts",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt9335498/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/demon-slayer.png",
  },
  {
    index: 3,
    releaseYear: "2016",
    name: "Your Name",
    genre: "Romance/Fantasy",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt5311514/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/Your-name.jpg",
  },
  {
    index: 4,
    releaseYear: "2021",
    name: "Jujutsu Kaisen",
    genre: "Adventure Dark fantasy Supernatural",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt12343534/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/jujutsu-kaisen.jpg",
  },
  {
    index: 5,
    releaseYear: "1999",
    name: "One Piece",
    genre: "Adventure Fantasy",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt0388629/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/one-piece.jpg",
  },
  {
    index: 6,
    releaseYear: "2019",
    name: "Weathering with you",
    genre: "Fantasy/Romance",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt9426210/",
    imgUrl:
      "https://www.yudiz.com/codepen/hover-reveal/weathering-with-you.jpg",
  },
  {
    index: 7,
    releaseYear: "2006",
    name: "Death Note",
    genre: "psychological thriller",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt0877057/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/death-note.jpg",
  },
  {
    index: 8,
    releaseYear: "1999",
    name: "Naruto",
    genre: "Adventure, Fantasy comedy, Martial arts",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt0409591/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/naruto.jpg",
  },
  {
    index: 9,
    releaseYear: "2022",
    name: "Suzume",
    genre: "Adventure/Animation",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt16428256/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/Suzume.jpg",
  },
  {
    index: 10,
    releaseYear: "1989",
    name: "Dragon Ball",
    genre: "Adventure, Fantasy, Martial arts",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt0280249/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/Dragon-ball.jpg",
  },
  {
    index: 11,
    releaseYear: "2021",
    name: "Arcane",
    genre: "Action, Adventure, Drama, Science fant...",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt11126994/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/jinx.jpg",
  },
  {
    index: 12,
    releaseYear: "2014",
    name: "Haikyuu",
    genre: "Comedy, Coming-of-age, Sports",
    redirectLink: "",
    imdbLink: "https://www.imdb.com/title/tt3398540/",
    imgUrl: "https://www.yudiz.com/codepen/hover-reveal/haikyuu.jpg",
  },
];
