export const demoTrendingData = {
  currentPage: 1,
  hasNextPage: true,
  results: [
    {
      id: "146066",
      malId: 51180,
      title: {
        romaji: "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season",
        english: "Classroom of the Elite Season 3",
        native: "ようこそ実力至上主義の教室へ 3rd Season",
        userPreferred:
          "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx146066-zzKl6P6OeEjy.jpg",
      imageHash: "hash",
      trailer: {
        id: "Z11Ozjk0ufY",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/Z11Ozjk0ufY/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "The third season of <i>Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e</i>.<br>\n<br>\nThe third semester kicks off in high gear with a special boot camp deep in the mountains. Forcibly separated into groups along grade and gender lines, the first, second and third years alike must work together to survive the rugged terrain. Even worse? The leader of the group that comes in last will be expelled. Can Class D make it back to campus intact, or is this where they finally say goodbye to one of their own?<br>\n<br>\n(Source: Seven Seas Entertainment)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/146066-gxjPUB1ofAO4.jpg",
      coverHash: "hash",
      rating: 78,
      releaseDate: 2024,
      color: "#bbd6f1",
      genres: ["Drama", "Psychological"],
      totalEpisodes: 13,
      duration: 24,
      type: "TV",
    },
    {
      id: "21",
      malId: 21,
      title: {
        romaji: "ONE PIECE",
        english: "ONE PIECE",
        native: "ONE PIECE",
        userPreferred: "ONE PIECE",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx21-tXMN3Y20PIL9.jpg",
      imageHash: "hash",
      trailer: {
        thumbnailHash: "hash",
      },
      description:
        "Gold Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and death of Roger by the World Government brought a change throughout the world. His last words before his death revealed the location of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece (which promises an unlimited amount of riches and fame), and quite possibly the most coveted of titles for the person who found it, the title of the Pirate King.<br><br>\nEnter Monkey D. Luffy, a 17-year-old boy that defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate who ransacks villages for fun, Luffy’s reason for being a pirate is one of pure wonder; the thought of an exciting adventure and meeting new and intriguing people, along with finding One Piece, are his reasons of becoming a pirate. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach One Piece.<br><br>\n<b>*This includes following special episodes:</b><br>\n- Chopperman to the Rescue! Protect the TV Station by the Shore! (Episode 336)<br>\n- The Strongest Tag-Team! Luffy and Toriko's Hard Struggle! (Episode 492)<br>\n- Team Formation! Save Chopper (Episode 542)<br>\n- History's Strongest Collaboration vs. Glutton of the Sea (Episode 590)<br>\n- 20th Anniversary! Special Romance Dawn (Episode 907)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
      coverHash: "hash",
      rating: 88,
      releaseDate: 1999,
      color: "#e4a15d",
      genres: ["Action", "Adventure", "Comedy", "Drama", "Fantasy"],
      totalEpisodes: 1094,
      duration: 24,
      type: "TV",
    },
    {
      id: "162780",
      malId: 54722,
      title: {
        romaji: "Mahou Shoujo ni Akogarete",
        english: "Gushing Over Magical Girls",
        native: "魔法少女にあこがれて",
        userPreferred: "Mahou Shoujo ni Akogarete",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx162780-brAdNEROhZdG.jpg",
      imageHash: "hash",
      trailer: {
        id: "hOgF0D8Pcjs",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/hOgF0D8Pcjs/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "Hiragi Utena is a major fangirl of the magical girls protecting her city, so when she has the chance to become one herself, she leaps at the chance to join their technicolor ranks… but when she transforms, she learns she isn’t fated to be a daring do-gooder, but rather a villain on the side of evil! At first she tries to quit her new gig as the leader of the local baddies, but she quickly realizes she enjoys it and is a total natural at tormenting the magical girls she loves so much. With both a bang and a whimper, Hiragi’s journey as a magical-girl-tormenting sadist has begun!<br>\n<br>\n(Source: HIDIVE)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/162780-rZ0KpsfCg2IA.jpg",
      coverHash: "hash",
      rating: 72,
      releaseDate: 2024,
      color: "#5da1e4",
      genres: ["Comedy", "Ecchi", "Mahou Shoujo", "Slice of Life"],
      totalEpisodes: 13,
      duration: 24,
      type: "TV",
    },
    {
      id: "162985",
      malId: 54794,
      title: {
        romaji: "Metallic Rouge",
        english: "Metallic Rouge",
        native: "メタリックルージュ",
        userPreferred: "Metallic Rouge",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx162985-3J7PrG5oO67v.jpg",
      imageHash: "hash",
      trailer: {
        id: "3GvzeHi8puU",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/3GvzeHi8puU/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "<i>Metallic Rouge</i> takes place in a a world where humans and androids coexist. The story follows Rouge, an android girl, who is on a mission on Mars with her partner Naomi. The mission is to murder nine artificial humans who are hostile to the government. <br><br>\n(Source: Anime News Network, edited)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/162985-cNJI3D7sLlrk.jpg",
      coverHash: "hash",
      rating: 66,
      releaseDate: 2024,
      color: "#e45da1",
      genres: ["Action", "Mystery", "Sci-Fi"],
      totalEpisodes: 7,
      duration: 23,
      type: "TV",
    },
    {
      id: "154587",
      malId: 52991,
      title: {
        romaji: "Sousou no Frieren",
        english: "Frieren: Beyond Journey’s End",
        native: "葬送のフリーレン",
        userPreferred: "Sousou no Frieren",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154587-n1fmjRv4JQUd.jpg",
      imageHash: "hash",
      trailer: {
        id: "qgQunxD0qCk",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/qgQunxD0qCk/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "The adventure is over but life goes on for an elf mage just beginning to learn what living is all about. Elf mage Frieren and her courageous fellow adventurers have defeated the Demon King and brought peace to the land. But Frieren will long outlive the rest of her former party. How will she come to understand what life means to the people around her? Decades after their victory, the funeral of one her friends confronts Frieren with her own near immortality. Frieren sets out to fulfill the last wishes of her comrades and finds herself beginning a new adventure…\n<br><br>\n(Source: Crunchyroll)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/154587-ivXNJ23SM1xB.jpg",
      coverHash: "hash",
      rating: 90,
      releaseDate: 2023,
      color: "#d6f1c9",
      genres: ["Adventure", "Drama", "Fantasy"],
      totalEpisodes: 28,
      duration: 24,
      type: "TV",
    },
    {
      id: "151807",
      malId: 52299,
      title: {
        romaji: "Ore dake Level Up na Ken",
        english: "Solo Leveling",
        native: "俺だけレベルアップな件",
        userPreferred: "Ore dake Level Up na Ken",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-m1gX3iwfIsLu.png",
      imageHash: "hash",
      trailer: {
        id: "HkIKAnwLZCw",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/HkIKAnwLZCw/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "They say whatever doesn’t kill you makes you stronger, but that’s not the case for the world’s weakest hunter Sung Jinwoo. After being brutally slaughtered by monsters in a high-ranking dungeon, Jinwoo came back with the System, a program only he could see, that’s leveling him up in every way. Now, he’s inspired to discover the secrets behind his powers and the dungeon that spawned them.<br>\n<br>\n(Source: Crunchyroll) <br><br>",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/151807-37yfQA3ym8PA.jpg",
      coverHash: "hash",
      rating: 83,
      releaseDate: 2024,
      color: "#28aef1",
      genres: ["Action", "Adventure", "Fantasy"],
      totalEpisodes: 12,
      duration: 24,
      type: "TV",
    },
    {
      id: "162144",
      malId: 54632,
      title: {
        romaji: "Gekai Elise",
        english: "Doctor Elise: The Royal Lady with the Lamp",
        native: "外科医エリーゼ",
        userPreferred: "Gekai Elise",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx162144-T0y7XyTFhSYJ.jpg",
      imageHash: "hash",
      trailer: {
        id: "3l7MMAZ2aas",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/3l7MMAZ2aas/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "Making up for her sins in a past life as the evil princess Elise, Aoi Takamoto dedicates her life to saving people as a doctor. But a fatal accident cuts her atonement short and suddenly she’s back to her previous life, 10 years before her death! Will her foresight and medical brilliance help her change her past ways and heal an ailing empire, or is fate doomed to repeat itself?\n<br><br>\n(Source: Crunchyroll)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx162144-T0y7XyTFhSYJ.jpg",
      coverHash: "hash",
      rating: 69,
      releaseDate: 2024,
      color: "#e4ae50",
      genres: ["Comedy", "Fantasy", "Romance"],
      totalEpisodes: 12,
      duration: 24,
      type: "TV",
    },
    {
      id: "143866",
      malId: 50803,
      title: {
        romaji: "Jaku-Chara Tomozaki-kun 2nd STAGE",
        english: "Bottom-Tier Character Tomozaki 2nd Stage",
        native: "弱キャラ友崎くん 2nd STAGE",
        userPreferred: "Jaku-Chara Tomozaki-kun 2nd STAGE",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx143866-u9sM4nUMJvGP.jpg",
      imageHash: "hash",
      trailer: {
        id: "w9qs5P3tKXc",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/w9qs5P3tKXc/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description: "The second season of <i>Jaku-Chara Tomozaki-kun</i>.",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/143866-dfIeGq0O9im5.jpg",
      coverHash: "hash",
      rating: 69,
      releaseDate: 2024,
      color: "#e4c993",
      genres: ["Comedy", "Drama", "Romance", "Slice of Life"],
      totalEpisodes: 13,
      duration: 24,
      type: "TV",
    },
    {
      id: "161645",
      malId: 54492,
      title: {
        romaji: "Kusuriya no Hitorigoto",
        english: "The Apothecary Diaries",
        native: "薬屋のひとりごと",
        userPreferred: "Kusuriya no Hitorigoto",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx161645-7I8Cip7XRDhV.jpg",
      imageHash: "hash",
      trailer: {
        id: "oyHqh8ue4zw",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/oyHqh8ue4zw/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "Maomao lived a peaceful life with her apothecary father. Until one day, she’s sold as a lowly servant to the emperor’s palace. But she wasn’t meant for a compliant life among royalty. So when imperial heirs fall ill, she decides to step in and find a cure! This catches the eye of Jinshi, a handsome palace official who promotes her. Now, she’s making a name for herself solving medical mysteries!\n<br><br>\n(Source: Crunchyroll)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/161645-oqzTZYIvviWI.jpg",
      coverHash: "hash",
      rating: 87,
      releaseDate: 2023,
      color: "#f1865d",
      genres: ["Drama", "Mystery"],
      totalEpisodes: 24,
      duration: 23,
      type: "TV",
    },
    {
      id: "163076",
      malId: 54837,
      title: {
        romaji:
          "Akuyaku Reijou Level 99: Watashi wa Ura Boss desu ga Maou de wa Arimasen",
        english:
          "Villainess Level 99: I May Be the Hidden Boss but I'm Not the Demon Lord",
        native: "悪役令嬢レベル99 ～私は裏ボスですが魔王ではありません～",
        userPreferred:
          "Akuyaku Reijou Level 99: Watashi wa Ura Boss desu ga Maou de wa Arimasen",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx163076-zwNndcqDSEGs.jpg",
      imageHash: "hash",
      trailer: {
        id: "ODtKada4LM0",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/ODtKada4LM0/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "This college kid wants nothing more than a quiet life. So when she’s reborn as Yumiella, the hidden villainess of an Otome RPG, she’s not exactly thrilled. Still yearning for peace, she abandons her evil duties to live a more discreet life. Until her gamer side kicks in and she accidentally reaches level 99! Now, everyone suspects that she’s the infamous Demon Lord. What future awaits her?<br>\n<br>\n(Source: Crunchyroll)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx163076-zwNndcqDSEGs.jpg",
      coverHash: "hash",
      rating: 73,
      releaseDate: 2024,
      color: "#e45050",
      genres: ["Comedy", "Fantasy", "Romance"],
      totalEpisodes: 12,
      duration: 24,
      type: "TV",
    },
    {
      id: "145064",
      malId: 51009,
      title: {
        romaji: "Jujutsu Kaisen 2nd Season",
        english: "JUJUTSU KAISEN Season 2",
        native: "呪術廻戦 第2期",
        userPreferred: "Jujutsu Kaisen 2nd Season",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx145064-oNJZtLWdXtvy.jpg",
      imageHash: "hash",
      trailer: {
        id: "O6qVieflwqs",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/O6qVieflwqs/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "The second season of <i>Jujutsu Kaisen</i>.<br>\n<br>\nThe past comes to light when second-year students Satoru Gojou and Suguru Getou are tasked with escorting young Riko Amanai to Master Tengen. But when a non-sorcerer user tries to kill them, their mission to protect the Star Plasma Vessel threatens to turn them into bitter enemies and cement their destinies—one as the world’s strongest sorcerer, and the other its most twisted curse user!<br>\n<br>\n(Source: Crunchyroll)",
      status: "Completed",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/145064-esDtAY2He7sk.jpg",
      coverHash: "hash",
      rating: 88,
      releaseDate: 2023,
      color: "#aeaee4",
      genres: ["Action", "Drama", "Supernatural"],
      totalEpisodes: 23,
      duration: 24,
      type: "TV",
    },
    {
      id: "151970",
      malId: 52347,
      title: {
        romaji: "Shangri-La Frontier",
        english: "Shangri-La Frontier",
        native: "シャングリラ・フロンティア",
        userPreferred: "Shangri-La Frontier",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151970-qFKtRhOaSqa0.jpg",
      imageHash: "hash",
      trailer: {
        id: "ZMpfkJiQrGg",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/ZMpfkJiQrGg/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        ' "When was the last time I played a game that wasn\'t crap?" This is a world in the near future where games that use display screens are classified as retro. Anything that can\'t keep up with state-of-the-art VR technology is called a "crap game," and you see a large number of crap games coming out. Those who devote their lives to clearing these games are called "crap-game hunters," and Rakuro Hizutome is one of them. The game he\'s chosen to tackle next is Shangri-La Frontier, a "god-tier game" that has a total of thirty million players. Online friends... An expansive world... Encounters with rivals... These are changing Rakuro and all the other players\' fates! The best game adventure tale by the strongest "crap game" player begins now!<br>\n<br>\n(Source: Crunchyroll)',
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/151970-Tnnfp0f7NOzj.jpg",
      coverHash: "hash",
      rating: 78,
      releaseDate: 2023,
      color: "#5da1e4",
      genres: ["Action", "Adventure", "Comedy", "Fantasy", "Sci-Fi"],
      totalEpisodes: 25,
      duration: 26,
      type: "TV",
    },
    {
      id: "167087",
      malId: 55973,
      title: {
        romaji: "30-sai made Doutei da to Mahou Tsukai ni Nareru Rashii",
        english:
          "Cherry Magic! Thirty Years of Virginity Can Make You a Wizard?!",
        native: "30歳まで童貞だと魔法使いになれるらしい",
        userPreferred: "30-sai made Doutei da to Mahou Tsukai ni Nareru Rashii",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx167087-3ZM69QhaQ3FE.jpg",
      imageHash: "hash",
      trailer: {
        id: "68ORi5SizCc",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/68ORi5SizCc/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "Adachi's 30th birthday as a virgin came with the oddest gift—the ability to read the mind of anyone he touches. Pondering what to do with this mysterious power, he gets a lead when he accidentally reads his colleague Kurosawa's mind. Turns out the handsome hotshot of the sales team has got a thing for him! How will Adachi respond to overhearing these affectionate thoughts?<br>\n<br>\n(Source: Crunchyroll)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx167087-3ZM69QhaQ3FE.jpg",
      coverHash: "hash",
      rating: 72,
      releaseDate: 2024,
      color: "#f1c9f1",
      genres: ["Comedy", "Romance", "Slice of Life", "Supernatural"],
      totalEpisodes: 12,
      duration: 24,
      type: "TV",
    },
    {
      id: "161476",
      malId: 54449,
      title: {
        romaji: "Ishura",
        english: "ISHURA",
        native: "異修羅",
        userPreferred: "Ishura",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx161476-ukTxAPHib1Fg.jpg",
      imageHash: "hash",
      trailer: {
        id: "k0-cO3zve7A",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/k0-cO3zve7A/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "In a world where the Demon King has died, a host of demigods capable of felling him have inherited the world: a master fencer who can figure out how to take out their opponent with a single glance; a lancer so swift they can break the sound barrier; a wyvern rogue who fights with three legendary weapons at once; an all-powerful wizard who can speak thoughts into being; and an angelic assassin who deals instant death. Eager to attain the title of “One True Hero,” these champions each pursue challenges against formidable foes and spark conflicts themselves. The battle to determine the mightiest of the mighty begins.<br><br>\n(Source: Yen Press)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/161476-jg6L0f8n19ak.jpg",
      coverHash: "hash",
      rating: 60,
      releaseDate: 2024,
      color: "#f1e4c9",
      genres: ["Action", "Drama", "Fantasy"],
      totalEpisodes: 12,
      duration: 24,
      type: "TV",
    },
    {
      id: "139518",
      malId: 49889,
      title: {
        romaji: "Tsuki ga Michibiku Isekai Douchuu 2nd Season",
        english: "TSUKIMICHI -Moonlit Fantasy- Season 2",
        native: "月が導く異世界道中 第二幕",
        userPreferred: "Tsuki ga Michibiku Isekai Douchuu 2nd Season",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx139518-SyBhWS7bi3z6.png",
      imageHash: "hash",
      trailer: {
        id: "bJaTrqUGXXU",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/bJaTrqUGXXU/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "The second season of <i>Tsuki ga Michibiku Isekai Douchuu</i>.<br>\n<br>\nAfter Makoto Misumi defeats Mitsurugi and Sofia Bulga, humanity is saved from the attacking demon army—for the time being. The goddess is aware of Makoto’s growing power, and she sees him as less of a nuisance and more of a rival. Makoto continues his journey to further expand his community of outcasts and connect with more hyumans. But will he be strong enough to hold off the coming storm?<br>\n<br>\n(Source: Crunchyroll)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/139518-OxLRGjPm9Tms.jpg",
      coverHash: "hash",
      rating: 76,
      releaseDate: 2024,
      color: "#f1865d",
      genres: ["Action", "Adventure", "Comedy", "Fantasy"],
      totalEpisodes: 25,
      duration: 24,
      type: "TV",
    },
    {
      id: "155963",
      malId: 53421,
      title: {
        romaji: "Dosanko Gal wa Namaramenkoi",
        english: "Hokkaido Gals Are Super Adorable!",
        native: "道産子ギャルはなまらめんこい",
        userPreferred: "Dosanko Gal wa Namaramenkoi",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx155963-kOnLUDAEamUe.jpg",
      imageHash: "hash",
      trailer: {
        id: "AwY-j4ZV570",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/AwY-j4ZV570/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "Snowflakes aren’t the only things dropping in Hokkaido—so are jaws, thanks to the super adorable gals who are turning the icy north into a hotbed of fashion and fun. Brace yourself for a winter storm of laughs, love, and killer outfits as these gals prove that being cute is an all-season affair. Here, frostbite meets fashionista!\n<br><br>\n(Source: Crunchyroll) ",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/155963-0YBhWU1chFHt.jpg",
      coverHash: "hash",
      rating: 69,
      releaseDate: 2024,
      color: "#d6ae6b",
      genres: ["Comedy", "Romance", "Slice of Life"],
      totalEpisodes: 12,
      duration: 24,
      type: "TV",
    },
    {
      id: "166610",
      malId: 55813,
      title: {
        romaji: "MASHLE: Kami Shinkakusha Kouho Senbatsu Shiken-hen",
        english: "MASHLE: MAGIC AND MUSCLES Season 2",
        native: "マッシュル-MASHLE- 神覚者候補選抜試験編",
        userPreferred: "MASHLE: Kami Shinkakusha Kouho Senbatsu Shiken-hen",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx166610-IjJ8YLOKsua4.jpg",
      imageHash: "hash",
      trailer: {
        id: "Al0Zin6iVCE",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/Al0Zin6iVCE/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "The second season of <i>MASHLE</i>, adapting the Divine Visionary Candidate Exam Arc.",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/166610-2gA4Vv20MVhv.jpg",
      coverHash: "hash",
      rating: 79,
      releaseDate: 2024,
      color: "#e48643",
      genres: ["Action", "Comedy", "Fantasy"],
      totalEpisodes: 12,
      duration: 24,
      type: "TV",
    },
    {
      id: "166794",
      malId: 55866,
      title: {
        romaji: "Yubisaki to Renren",
        english: "A Sign of Affection",
        native: "ゆびさきと恋々",
        userPreferred: "Yubisaki to Renren",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx166794-veSLL0zrrBhp.jpg",
      imageHash: "hash",
      trailer: {
        id: "hJd9FxYWzL0",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/hJd9FxYWzL0/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "Yuki Itose is just a typical student dealing with the pressures of college. She is struggling one day on the train when an upperclassman named Itsuomi Nagi helps her out. As he gradually opens a new world to her, Yuki develops feelings for Itsuomi. A pure love story begins to grow.<br>\n<br>\n(Source: Crunchyroll) ",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/166794-11TpGckiG12q.jpg",
      coverHash: "hash",
      rating: 82,
      releaseDate: 2024,
      color: "#e4a15d",
      genres: ["Romance", "Slice of Life"],
      totalEpisodes: 12,
      duration: 24,
      type: "TV",
    },
    {
      id: "168194",
      malId: 56242,
      title: {
        romaji: "Sengoku Youko",
        english: "Sengoku Youko",
        native: "戦国妖狐",
        userPreferred: "Sengoku Youko",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx168194-I7O79icUs0ou.jpg",
      imageHash: "hash",
      trailer: {
        id: "RblpbHLx6ZA",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/RblpbHLx6ZA/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "The world is divided into two factions: humans and monsters called katawara. Despite being a katawara, Tama loves humans and vows to protect them from evil, even if it means fighting her own kind. Her brother Jinka, however, hates humans, despite mostly being one. The siblings are joined by a cowardly swordsman named Shinsuke, who wants to learn how to become strong.<br>\n<br>\nWhen the group uncovers a plot to experiment on humans and transform them into monsters, they vow to defeat whoever is behind it... Even if it means battling an entire army of warriors.<br>\n<br>\n(Source: Crunchyroll)",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/168194-ynjLJ3TembGL.jpg",
      coverHash: "hash",
      rating: 65,
      releaseDate: 2024,
      color: "#f18650",
      genres: ["Action", "Adventure", "Fantasy"],
      totalEpisodes: 37,
      duration: 24,
      type: "TV",
    },
    {
      id: "153518",
      malId: 52701,
      title: {
        romaji: "Dungeon Meshi",
        english: "Delicious in Dungeon",
        native: "ダンジョン飯",
        userPreferred: "Dungeon Meshi",
      },
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx153518-7FNR7zCxO2X5.jpg",
      imageHash: "hash",
      trailer: {
        id: "RtpYObV4c1Y",
        site: "youtube",
        thumbnail: "https://i.ytimg.com/vi/RtpYObV4c1Y/hqdefault.jpg",
        thumbnailHash: "hash",
      },
      description:
        "When young adventurer Laios and his company are attacked and soundly thrashed by a dragon deep in a dungeon, the party loses all its money and provisions...and a member! They're eager to go back and save her, but there is just one problem: If they set out with no food or coin to speak of, they're sure to starve on the way! But Laios comes up with a brilliant idea: \"Let's eat the monsters!\" Slimes, basilisks, and even dragons...none are safe from the appetites of these dungeon-crawling gourmands! <br>\n<br>\n(Source: Yen Press)\n<br><br>\n<i>Note: A world premiere screening of Episode 1 was shown in the Studio TRIGGER panel at Anime Expo on July 1, 2023.</i>",
      status: "Ongoing",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/153518-7uRvV7SLqmHV.jpg",
      coverHash: "hash",
      rating: 77,
      releaseDate: 2024,
      color: "#e48643",
      genres: ["Adventure", "Comedy", "Fantasy"],
      totalEpisodes: 24,
      duration: 25,
      type: "TV",
    },
  ],
};
