export const demoSummer = {
  currentPage: 1,
  hasNextPage: true,
  totalPages: 1000,
  totalResults: 5000,
  results: [
    {
      id: "16498",
      malId: 16498,
      title: {
        romaji: "Shingeki no Kyojin",
        english: "Attack on Titan",
        native: "進撃の巨人",
        userPreferred: "Shingeki no Kyojin",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-C6FPmWm59CyP.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8jpFCOcDmneX.jpg",
      coverHash: "hash",
      popularity: 745638,
      totalEpisodes: 25,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Several hundred years ago, humans were nearly exterminated by titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest of titans.<br><br>\r\nFlash forward to the present and the city has not seen a titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a colossal titan that appears out of thin air. As the smaller titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single titan and take revenge for all of mankind.<br><br>\r\n(Source: MangaHelpers) ",
      genres: ["Action", "Drama", "Fantasy", "Mystery"],
      rating: 84,
      color: "#e4a15d",
      type: "TV",
      releaseDate: 2013,
    },
    {
      id: "101922",
      malId: 38000,
      title: {
        romaji: "Kimetsu no Yaiba",
        english: "Demon Slayer: Kimetsu no Yaiba",
        native: "鬼滅の刃",
        userPreferred: "Kimetsu no Yaiba",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-PEn1CTc93blC.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-YfZhKBUDDS6L.jpg",
      coverHash: "hash",
      popularity: 704090,
      totalEpisodes: 26,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.<br>\n<br>\n(Source: Crunchyroll)",
      genres: ["Action", "Adventure", "Drama", "Fantasy", "Supernatural"],
      rating: 83,
      color: "#4B4A95",
      type: "TV",
      releaseDate: 2019,
    },
    {
      id: "21459",
      malId: 31964,
      title: {
        romaji: "Boku no Hero Academia",
        english: "My Hero Academia",
        native: "僕のヒーローアカデミア",
        userPreferred: "Boku no Hero Academia",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21459-DUKLgasrgeNO.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21459-yeVkolGKdGUV.jpg",
      coverHash: "hash",
      popularity: 647963,
      totalEpisodes: 13,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "What would the world be like if 80 percent of the population manifested extraordinary superpowers called “Quirks” at age four? Heroes and villains would be battling it out everywhere! Becoming a hero would mean learning to use your power, but where would you go to study? U.A. High's Hero Program of course! But what would you do if you were one of the 20 percent who were born Quirkless?<br><br>\n\nMiddle school student Izuku Midoriya wants to be a hero more than anything, but he hasn't got an ounce of power in him. With no chance of ever getting into the prestigious U.A. High School for budding heroes, his life is looking more and more like a dead end. Then an encounter with All Might, the greatest hero of them all gives him a chance to change his destiny…<br><br>\n\n(Source: Viz Media)",
      genres: ["Action", "Adventure", "Comedy"],
      rating: 77,
      color: "#e4c935",
      type: "TV",
      releaseDate: 2016,
    },
    {
      id: "20958",
      malId: 25777,
      title: {
        romaji: "Shingeki no Kyojin 2",
        english: "Attack on Titan Season 2",
        native: "進撃の巨人２",
        userPreferred: "Shingeki no Kyojin 2",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20958-HuFJyr54Mmir.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20958-Y7eQdz9VENBD.jpg",
      coverHash: "hash",
      popularity: 533537,
      totalEpisodes: 12,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Eren Jaeger swore to wipe out every last Titan, but in a battle for his life he wound up becoming the thing he hates most. With his new powers, he fights for humanity's freedom facing the monsters that threaten his home. After a bittersweet victory against the Female Titan, Eren finds no time to rest—a horde of Titans is approaching Wall Rose and the battle for humanity continues!<br><br>\n\n(Source: Funimation)",
      genres: ["Action", "Drama", "Fantasy", "Mystery"],
      rating: 84,
      color: "#6AA66F",
      type: "TV",
      releaseDate: 2017,
    },
    {
      id: "5114",
      malId: 5114,
      title: {
        romaji: "Hagane no Renkinjutsushi: FULLMETAL ALCHEMIST",
        english: "Fullmetal Alchemist: Brotherhood",
        native: "鋼の錬金術師 FULLMETAL ALCHEMIST",
        userPreferred: "Hagane no Renkinjutsushi: FULLMETAL ALCHEMIST",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx5114-KJTQz9AIm6Wk.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/5114-q0V5URebphSG.jpg",
      coverHash: "hash",
      popularity: 522163,
      totalEpisodes: 64,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "\"In order for something to be obtained, something of equal value must be lost.\"\n<br><br>\nAlchemy is bound by this Law of Equivalent Exchange—something the young brothers Edward and Alphonse Elric only realize after attempting human transmutation: the one forbidden act of alchemy. They pay a terrible price for their transgression—Edward loses his left leg, Alphonse his physical body. It is only by the desperate sacrifice of Edward's right arm that he is able to affix Alphonse's soul to a suit of armor. Devastated and alone, it is the hope that they would both eventually return to their original bodies that gives Edward the inspiration to obtain metal limbs called \"automail\" and become a state alchemist, the Fullmetal Alchemist.\n<br><br>\nThree years of searching later, the brothers seek the Philosopher's Stone, a mythical relic that allows an alchemist to overcome the Law of Equivalent Exchange. Even with military allies Colonel Roy Mustang, Lieutenant Riza Hawkeye, and Lieutenant Colonel Maes Hughes on their side, the brothers find themselves caught up in a nationwide conspiracy that leads them not only to the true nature of the elusive Philosopher's Stone, but their country's murky history as well. In between finding a serial killer and racing against time, Edward and Alphonse must ask themselves if what they are doing will make them human again... or take away their humanity.\n<br><br>\n(Source: MAL Rewrite)",
      genres: ["Action", "Adventure", "Drama", "Fantasy"],
      rating: 90,
      color: "#e4c993",
      type: "TV",
      releaseDate: 2009,
    },
  ],
};
