export const demoFall = {
  currentPage: 1,
  hasNextPage: true,
  totalPages: 1000,
  totalResults: 5000,
  results: [
    {
      id: "1535",
      malId: 1535,
      title: {
        romaji: "DEATH NOTE",
        english: "Death Note",
        native: "DEATH NOTE",
        userPreferred: "DEATH NOTE",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-lawCwhzhi96X.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1535.jpg",
      coverHash: "hash",
      popularity: 678443,
      totalEpisodes: 37,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Light Yagami is a genius high school student who is about to learn about life through a book of death. When a bored shinigami, a God of Death, named Ryuk drops a black notepad called a <i>Death Note</i>, Light receives power over life and death with the stroke of a pen. Determined to use this dark gift for the best, Light sets out to rid the world of evil… namely, the people he believes to be evil. Should anyone hold such power?<br>\n<br>\nThe consequences of Light’s actions will set the world ablaze.<br>\n<br>\n(Source: Viz Media)",
      genres: ["Mystery", "Psychological", "Supernatural", "Thriller"],
      rating: 84,
      color: null,
      type: "TV",
      releaseDate: 2006,
    },
    {
      id: "113415",
      malId: 40748,
      title: {
        romaji: "Jujutsu Kaisen",
        english: "JUJUTSU KAISEN",
        native: "呪術廻戦",
        userPreferred: "Jujutsu Kaisen",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pEFseh.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/113415-jQBSkxWAAk83.jpg",
      coverHash: "hash",
      popularity: 639407,
      totalEpisodes: 24,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        'A boy fights... for "the right death."<br>\n<br>\nHardship, regret, shame: the negative feelings that humans feel become Curses that lurk in our everyday lives. The Curses run rampant throughout the world, capable of leading people to terrible misfortune and even death. What\'s more, the Curses can only be exorcised by another Curse.<br>\n<br>\nItadori Yuji is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a friend who has been attacked by Curses, he eats the finger of the Double-Faced Specter, taking the Curse into his own soul. From then on, he shares one body with the Double-Faced Specter. Guided by the most powerful of sorcerers, Gojou Satoru, Itadori is admitted to the Tokyo Metropolitan Technical High School of Sorcery, an organization that fights the Curses... and thus begins the heroic tale of a boy who became a Curse to exorcise a Curse, a life from which he could never turn back.\n<br><br>\n(Source: Crunchyroll)<br>\n<br>\n<i>Note: The first episode received an early web premiere on September 19th, 2020. The regular TV broadcast started on October 3rd, 2020.</i>',
      genres: ["Action", "Drama", "Supernatural"],
      rating: 86,
      color: "#e45d5d",
      type: "TV",
      releaseDate: 2020,
    },
    {
      id: "11061",
      malId: 11061,
      title: {
        romaji: "HUNTER×HUNTER (2011)",
        english: "Hunter x Hunter (2011)",
        native: "HUNTER×HUNTER (2011)",
        userPreferred: "HUNTER×HUNTER (2011)",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-sIpBprNRfzCe.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/11061-8WkkTZ6duKpq.jpg",
      coverHash: "hash",
      popularity: 606872,
      totalEpisodes: 148,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "A new adaption of the manga of the same name by Togashi Yoshihiro.<br><br>\nA Hunter is one who travels the world doing all sorts of dangerous tasks. From capturing criminals to searching deep within uncharted lands for any lost treasures. Gon is a young boy whose father disappeared long ago, being a Hunter. He believes if he could also follow his father's path, he could one day reunite with him.<br><br>\nAfter becoming 12, Gon leaves his home and takes on the task of entering the Hunter exam, notorious for its low success rate and high probability of death to become an official Hunter. He befriends the revenge-driven Kurapika, the doctor-to-be Leorio and the rebellious ex-assassin Killua in the exam, with their friendship prevailing throughout the many trials and threats they come upon taking on the dangerous career of a Hunter.",
      genres: ["Action", "Adventure", "Fantasy"],
      rating: 89,
      color: "#f1d65d",
      type: "TV",
      releaseDate: 2011,
    },
    {
      id: "21087",
      malId: 30276,
      title: {
        romaji: "One Punch Man",
        english: "One-Punch Man",
        native: "ワンパンマン",
        userPreferred: "One Punch Man",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21087-UV2tu6exrfXz.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21087-sHb9zUZFsHe1.jpg",
      coverHash: "hash",
      popularity: 564495,
      totalEpisodes: 12,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Saitama has a rather peculiar hobby, being a superhero, but despite his heroic deeds and superhuman abilities, a shadow looms over his life. He's become much too powerful, to the point that every opponent ends up defeated with a single punch.\n<br><br>\nThe lack of challenge has driven him into a state of apathy, as he watches his life pass by having lost all enthusiasm, at least until he's unwillingly thrust in the role of being a mentor to the young and revenge-driven Genos.   \n\n",
      genres: ["Action", "Comedy", "Sci-Fi", "Supernatural"],
      rating: 83,
      color: "#e4ae5d",
      type: "TV",
      releaseDate: 2015,
    },
    {
      id: "20",
      malId: 20,
      title: {
        romaji: "NARUTO",
        english: "Naruto",
        native: "NARUTO -ナルト-",
        userPreferred: "NARUTO",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20-YJvLbgJQPCoI.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20-HHxhPj5JD13a.jpg",
      coverHash: "hash",
      popularity: 518700,
      totalEpisodes: 220,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Naruto Uzumaki, a hyperactive and knuckle-headed ninja, lives in Konohagakure, the Hidden Leaf village. Moments prior to his birth, a huge demon known as the Kyuubi, the Nine-tailed Fox, attacked Konohagakure and wreaked havoc. In order to put an end to the Kyuubi's rampage, the leader of the village, the 4th Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto. <br><br>\nShunned because of the presence of the Kyuubi inside him, Naruto struggles to find his place in the village. He strives to become the Hokage of Konohagakure, and he meets many friends and foes along the way. <br><br>\n(Source: MAL Rewrite)",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Supernatural",
      ],
      rating: 79,
      color: "#e47850",
      type: "TV",
      releaseDate: 2002,
    },
  ],
};
