export const demoSpring = {
  currentPage: 1,
  hasNextPage: true,
  totalPages: 1000,
  totalResults: 5000,
  results: [
    {
      id: "20605",
      malId: 22319,
      title: {
        romaji: "Tokyo Ghoul",
        english: "Tokyo Ghoul",
        native: "東京喰種 トーキョーグール",
        userPreferred: "Tokyo Ghoul",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx20605-fmnHdfurM7m6.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20605-RCJ7M71zLmrh.jpg",
      coverHash: "hash",
      popularity: 541157,
      totalEpisodes: 12,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        'The suspense horror/dark fantasy story is set in Tokyo, which is haunted by mysterious "ghouls" who are devouring humans. People are gripped by the fear of these ghouls whose identities are masked in mystery. An ordinary college student named Kaneki encounters Rize, a girl who is an avid reader like him, at the café he frequents. Little does he realize that his fate will change overnight.\n<br><br>\n(Source: Anime News Network)',
      genres: [
        "Action",
        "Drama",
        "Horror",
        "Mystery",
        "Psychological",
        "Supernatural",
      ],
      rating: 75,
      color: "#35DDFF",
      type: "TV",
      releaseDate: 2014,
    },
    {
      id: "11757",
      malId: 11757,
      title: {
        romaji: "Sword Art Online",
        english: "Sword Art Online",
        native: "ソードアート・オンライン",
        userPreferred: "Sword Art Online",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx11757-Q9P2zjCPICq5.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/11757-TlEEV9weG4Ag.jpg",
      coverHash: "hash",
      popularity: 530339,
      totalEpisodes: 25,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "In the near future, a Virtual Reality Massive Multiplayer Online Role-Playing Game (VRMMORPG) called Sword Art Online has been released where players control their avatars with their bodies using a piece of technology called Nerve Gear. One day, players discover they cannot log out, as the game creator is holding them captive unless they reach the 100th floor of the game's tower and defeat the final boss. However, if they die in the game, they die in real life. Their struggle for survival starts now...<br><br>\n(Source: Crunchyroll)",
      genres: ["Action", "Adventure", "Fantasy", "Romance"],
      rating: 69,
      color: "#5DC0E4",
      type: "TV",
      releaseDate: 2012,
    },
    {
      id: "21519",
      malId: 32281,
      title: {
        romaji: "Kimi no Na wa.",
        english: "Your Name.",
        native: "君の名は。",
        userPreferred: "Kimi no Na wa.",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21519-XIr3PeczUjjF.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21519-1ayMXgNlmByb.jpg",
      coverHash: "hash",
      popularity: 504517,
      totalEpisodes: 1,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture.<br>\n<br>\nOne day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki's body! Elsewhere, Taki finds himself living Mitsuha's life in the humble countryside. In pursuit of an answer to this strange phenomenon, they begin to search for one another.<br>\n<br>\n<i>Kimi no Na wa.</i> revolves around Mitsuha and Taki's actions, which begin to have a dramatic impact on each other's lives, weaving them into a fabric held together by fate and circumstance.<br>\n<br>\n(Source: MAL Rewrite)",
      genres: ["Drama", "Romance", "Supernatural"],
      rating: 85,
      color: "#0da1e4",
      type: "MOVIE",
      releaseDate: 2016,
    },
    {
      id: "99147",
      malId: 35760,
      title: {
        romaji: "Shingeki no Kyojin 3",
        english: "Attack on Titan Season 3",
        native: "進撃の巨人３",
        userPreferred: "Shingeki no Kyojin 3",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx99147-5RXELRvwjFl6.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/99147-HACsFVrynFf5.jpg",
      coverHash: "hash",
      popularity: 495406,
      totalEpisodes: 12,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Eren and his companions in the 104th are assigned to the newly-formed Levi Squad, whose assignment is to keep Eren and Historia safe given Eren's newly-discovered power and Historia's knowledge and pedigree. Levi and Erwin have good reason to be concerned, because the priest of the Church that Hanji had hidden away was found tortured to death, making it clear that the Military Police are involved with the cover-up. Things get more harrowing when the MPs make a move on Erwin and the Levi Squad narrowly avoids capture. Eren is also having problems with his Titan transformation, and a deadly killer has been hired to secure Eren and Historia, one Levi knows all too well from his youth.<br>\n<br>\n(Source: Anime News Network)",
      genres: ["Action", "Drama", "Fantasy", "Mystery"],
      rating: 85,
      color: "#4386e4",
      type: "TV",
      releaseDate: 2018,
    },
    {
      id: "20954",
      malId: 28851,
      title: {
        romaji: "Koe no Katachi",
        english: "A Silent Voice",
        native: "聲の形",
        userPreferred: "Koe no Katachi",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20954-UMb6Kl7ZL8Ke.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20954-f30bHMXa5Qoe.jpg",
      coverHash: "hash",
      popularity: 491871,
      totalEpisodes: 1,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "After transferring into a new school, a deaf girl, Shouko Nishimiya, is bullied by the popular Shouya Ishida. As Shouya continues to bully Shouko, the class turns its back on him. Shouko transfers and Shouya grows up as an outcast. Alone and depressed, the regretful Shouya finds Shouko to make amends.\n<br><br>\n(Source: Eleven Arts)",
      genres: ["Drama", "Romance", "Slice of Life"],
      rating: 88,
      color: "#5dbbe4",
      type: "MOVIE",
      releaseDate: 2016,
    },
  ],
};
