export const demoFavourite = {
  currentPage: 1,
  hasNextPage: true,
  totalPages: 250,
  totalResults: 5000,
  results: [
    {
      id: "21",
      malId: 21,
      title: {
        romaji: "ONE PIECE",
        english: "ONE PIECE",
        native: "ONE PIECE",
        userPreferred: "ONE PIECE",
      },
      status: "Ongoing",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx21-tXMN3Y20PIL9.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
      coverHash: "hash",
      popularity: 500070,
      totalEpisodes: 1094,
      currentEpisode: 1094,
      countryOfOrigin: "JP",
      description:
        "Gold Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and death of Roger by the World Government brought a change throughout the world. His last words before his death revealed the location of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece (which promises an unlimited amount of riches and fame), and quite possibly the most coveted of titles for the person who found it, the title of the Pirate King.<br><br>\nEnter Monkey D. Luffy, a 17-year-old boy that defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate who ransacks villages for fun, Luffy’s reason for being a pirate is one of pure wonder; the thought of an exciting adventure and meeting new and intriguing people, along with finding One Piece, are his reasons of becoming a pirate. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach One Piece.<br><br>\n<b>*This includes following special episodes:</b><br>\n- Chopperman to the Rescue! Protect the TV Station by the Shore! (Episode 336)<br>\n- The Strongest Tag-Team! Luffy and Toriko's Hard Struggle! (Episode 492)<br>\n- Team Formation! Save Chopper (Episode 542)<br>\n- History's Strongest Collaboration vs. Glutton of the Sea (Episode 590)<br>\n- 20th Anniversary! Special Romance Dawn (Episode 907)",
      genres: ["Action", "Adventure", "Comedy", "Drama", "Fantasy"],
      rating: 88,
      color: "#e4a15d",
      type: "TV",
      releaseDate: 1999,
    },
    {
      id: "11061",
      malId: 11061,
      title: {
        romaji: "HUNTER×HUNTER (2011)",
        english: "Hunter x Hunter (2011)",
        native: "HUNTER×HUNTER (2011)",
        userPreferred: "HUNTER×HUNTER (2011)",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-sIpBprNRfzCe.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/11061-8WkkTZ6duKpq.jpg",
      coverHash: "hash",
      popularity: 606700,
      totalEpisodes: 148,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "A new adaption of the manga of the same name by Togashi Yoshihiro.<br><br>\nA Hunter is one who travels the world doing all sorts of dangerous tasks. From capturing criminals to searching deep within uncharted lands for any lost treasures. Gon is a young boy whose father disappeared long ago, being a Hunter. He believes if he could also follow his father's path, he could one day reunite with him.<br><br>\nAfter becoming 12, Gon leaves his home and takes on the task of entering the Hunter exam, notorious for its low success rate and high probability of death to become an official Hunter. He befriends the revenge-driven Kurapika, the doctor-to-be Leorio and the rebellious ex-assassin Killua in the exam, with their friendship prevailing throughout the many trials and threats they come upon taking on the dangerous career of a Hunter.",
      genres: ["Action", "Adventure", "Fantasy"],
      rating: 89,
      color: "#f1d65d",
      type: "TV",
      releaseDate: 2011,
    },
    {
      id: "16498",
      malId: 16498,
      title: {
        romaji: "Shingeki no Kyojin",
        english: "Attack on Titan",
        native: "進撃の巨人",
        userPreferred: "Shingeki no Kyojin",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-C6FPmWm59CyP.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8jpFCOcDmneX.jpg",
      coverHash: "hash",
      popularity: 745638,
      totalEpisodes: 25,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Several hundred years ago, humans were nearly exterminated by titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest of titans.<br><br>\r\nFlash forward to the present and the city has not seen a titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a colossal titan that appears out of thin air. As the smaller titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single titan and take revenge for all of mankind.<br><br>\r\n(Source: MangaHelpers) ",
      genres: ["Action", "Drama", "Fantasy", "Mystery"],
      rating: 84,
      color: "#e4a15d",
      type: "TV",
      releaseDate: 2013,
    },
    {
      id: "113415",
      malId: 40748,
      title: {
        romaji: "Jujutsu Kaisen",
        english: "JUJUTSU KAISEN",
        native: "呪術廻戦",
        userPreferred: "Jujutsu Kaisen",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pEFseh.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/113415-jQBSkxWAAk83.jpg",
      coverHash: "hash",
      popularity: 639407,
      totalEpisodes: 24,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        'A boy fights... for "the right death."<br>\n<br>\nHardship, regret, shame: the negative feelings that humans feel become Curses that lurk in our everyday lives. The Curses run rampant throughout the world, capable of leading people to terrible misfortune and even death. What\'s more, the Curses can only be exorcised by another Curse.<br>\n<br>\nItadori Yuji is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a friend who has been attacked by Curses, he eats the finger of the Double-Faced Specter, taking the Curse into his own soul. From then on, he shares one body with the Double-Faced Specter. Guided by the most powerful of sorcerers, Gojou Satoru, Itadori is admitted to the Tokyo Metropolitan Technical High School of Sorcery, an organization that fights the Curses... and thus begins the heroic tale of a boy who became a Curse to exorcise a Curse, a life from which he could never turn back.\n<br><br>\n(Source: Crunchyroll)<br>\n<br>\n<i>Note: The first episode received an early web premiere on September 19th, 2020. The regular TV broadcast started on October 3rd, 2020.</i>',
      genres: ["Action", "Drama", "Supernatural"],
      rating: 86,
      color: "#e45d5d",
      type: "TV",
      releaseDate: 2020,
    },
    {
      id: "5114",
      malId: 5114,
      title: {
        romaji: "Hagane no Renkinjutsushi: FULLMETAL ALCHEMIST",
        english: "Fullmetal Alchemist: Brotherhood",
        native: "鋼の錬金術師 FULLMETAL ALCHEMIST",
        userPreferred: "Hagane no Renkinjutsushi: FULLMETAL ALCHEMIST",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx5114-KJTQz9AIm6Wk.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/5114-q0V5URebphSG.jpg",
      coverHash: "hash",
      popularity: 521980,
      totalEpisodes: 64,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "\"In order for something to be obtained, something of equal value must be lost.\"\n<br><br>\nAlchemy is bound by this Law of Equivalent Exchange—something the young brothers Edward and Alphonse Elric only realize after attempting human transmutation: the one forbidden act of alchemy. They pay a terrible price for their transgression—Edward loses his left leg, Alphonse his physical body. It is only by the desperate sacrifice of Edward's right arm that he is able to affix Alphonse's soul to a suit of armor. Devastated and alone, it is the hope that they would both eventually return to their original bodies that gives Edward the inspiration to obtain metal limbs called \"automail\" and become a state alchemist, the Fullmetal Alchemist.\n<br><br>\nThree years of searching later, the brothers seek the Philosopher's Stone, a mythical relic that allows an alchemist to overcome the Law of Equivalent Exchange. Even with military allies Colonel Roy Mustang, Lieutenant Riza Hawkeye, and Lieutenant Colonel Maes Hughes on their side, the brothers find themselves caught up in a nationwide conspiracy that leads them not only to the true nature of the elusive Philosopher's Stone, but their country's murky history as well. In between finding a serial killer and racing against time, Edward and Alphonse must ask themselves if what they are doing will make them human again... or take away their humanity.\n<br><br>\n(Source: MAL Rewrite)",
      genres: ["Action", "Adventure", "Drama", "Fantasy"],
      rating: 90,
      color: "#e4c993",
      type: "TV",
      releaseDate: 2009,
    },
    {
      id: "101922",
      malId: 38000,
      title: {
        romaji: "Kimetsu no Yaiba",
        english: "Demon Slayer: Kimetsu no Yaiba",
        native: "鬼滅の刃",
        userPreferred: "Kimetsu no Yaiba",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-PEn1CTc93blC.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-YfZhKBUDDS6L.jpg",
      coverHash: "hash",
      popularity: 704090,
      totalEpisodes: 26,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.<br>\n<br>\n(Source: Crunchyroll)",
      genres: ["Action", "Adventure", "Drama", "Fantasy", "Supernatural"],
      rating: 83,
      color: "#4B4A95",
      type: "TV",
      releaseDate: 2019,
    },
    {
      id: "9253",
      malId: 9253,
      title: {
        romaji: "Steins;Gate",
        english: "Steins;Gate",
        native: "シュタインズ・ゲート",
        userPreferred: "Steins;Gate",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx9253-7pdcVzQSkKxT.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/n9253-JIhmKgBKsWUN.jpg",
      coverHash: "hash",
      popularity: 432239,
      totalEpisodes: 24,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        'Self-proclaimed mad scientist Okabe Rintarou lives in a small room in Akihabara, where he invents "future gadgets" with fellow lab members Shiina Mayuri, his air-headed childhood friend, and Hashida Itaru, an otaku hacker. The three pass the time by tinkering with their latest creation, a "Phone Microwave" that can be controlled through text messages. \n<br><br>\nThe lab members soon face a string of mysterious incidents that lead to a game-changing discovery: the Phone Microwave can send emails to the past and thus alter history. Adapted from the critically acclaimed visual novel by 5pb. and Nitroplus, Steins;Gate takes Okabe to the depths of scientific theory and human despair as he faces the dire consequences of changing the past.',
      genres: ["Drama", "Psychological", "Sci-Fi", "Thriller"],
      rating: 89,
      color: "#e4a15d",
      type: "TV",
      releaseDate: 2011,
    },
    {
      id: "20954",
      malId: 28851,
      title: {
        romaji: "Koe no Katachi",
        english: "A Silent Voice",
        native: "聲の形",
        userPreferred: "Koe no Katachi",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20954-UMb6Kl7ZL8Ke.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20954-f30bHMXa5Qoe.jpg",
      coverHash: "hash",
      popularity: 491871,
      totalEpisodes: 1,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "After transferring into a new school, a deaf girl, Shouko Nishimiya, is bullied by the popular Shouya Ishida. As Shouya continues to bully Shouko, the class turns its back on him. Shouko transfers and Shouya grows up as an outcast. Alone and depressed, the regretful Shouya finds Shouko to make amends.\n<br><br>\n(Source: Eleven Arts)",
      genres: ["Drama", "Romance", "Slice of Life"],
      rating: 88,
      color: "#5dbbe4",
      type: "MOVIE",
      releaseDate: 2016,
    },
    {
      id: "1535",
      malId: 1535,
      title: {
        romaji: "DEATH NOTE",
        english: "Death Note",
        native: "DEATH NOTE",
        userPreferred: "DEATH NOTE",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-lawCwhzhi96X.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1535.jpg",
      coverHash: "hash",
      popularity: 678174,
      totalEpisodes: 37,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Light Yagami is a genius high school student who is about to learn about life through a book of death. When a bored shinigami, a God of Death, named Ryuk drops a black notepad called a <i>Death Note</i>, Light receives power over life and death with the stroke of a pen. Determined to use this dark gift for the best, Light sets out to rid the world of evil… namely, the people he believes to be evil. Should anyone hold such power?<br>\n<br>\nThe consequences of Light’s actions will set the world ablaze.<br>\n<br>\n(Source: Viz Media)",
      genres: ["Mystery", "Psychological", "Supernatural", "Thriller"],
      rating: 84,
      color: null,
      type: "TV",
      releaseDate: 2006,
    },
    {
      id: "21519",
      malId: 32281,
      title: {
        romaji: "Kimi no Na wa.",
        english: "Your Name.",
        native: "君の名は。",
        userPreferred: "Kimi no Na wa.",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21519-XIr3PeczUjjF.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21519-1ayMXgNlmByb.jpg",
      coverHash: "hash",
      popularity: 504517,
      totalEpisodes: 1,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture.<br>\n<br>\nOne day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki's body! Elsewhere, Taki finds himself living Mitsuha's life in the humble countryside. In pursuit of an answer to this strange phenomenon, they begin to search for one another.<br>\n<br>\n<i>Kimi no Na wa.</i> revolves around Mitsuha and Taki's actions, which begin to have a dramatic impact on each other's lives, weaving them into a fabric held together by fate and circumstance.<br>\n<br>\n(Source: MAL Rewrite)",
      genres: ["Drama", "Romance", "Supernatural"],
      rating: 85,
      color: "#0da1e4",
      type: "MOVIE",
      releaseDate: 2016,
    },
    {
      id: "1735",
      malId: 1735,
      title: {
        romaji: "NARUTO: Shippuuden",
        english: "Naruto: Shippuden",
        native: "NARUTO -ナルト- 疾風伝",
        userPreferred: "NARUTO: Shippuuden",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1735-Az5gbEdWeotG.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1735.jpg",
      coverHash: "hash",
      popularity: 441907,
      totalEpisodes: 500,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Naruto: Shippuuden is the continuation of the original animated TV series Naruto. The story revolves around an older and slightly more matured Uzumaki Naruto and his quest to save his friend Uchiha Sasuke from the grips of the snake-like Shinobi, Orochimaru. After 2 and a half years Naruto finally returns to his village of Konoha, and sets about putting his ambitions to work, though it will not be easy, as he has amassed a few (more dangerous) enemies, in the likes of the shinobi organization; Akatsuki. <br><br>\n(Source: Anime News Network)",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Supernatural",
      ],
      rating: 81,
      color: "#e4865d",
      type: "TV",
      releaseDate: 2007,
    },
    {
      id: "30",
      malId: 30,
      title: {
        romaji: "Shin Seiki Evangelion",
        english: "Neon Genesis Evangelion",
        native: "新世紀エヴァンゲリオン",
        userPreferred: "Shin Seiki Evangelion",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx30-wmNoX3m2qTzz.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/30-gEMoHHIqxDgN.jpg",
      coverHash: "hash",
      popularity: 340551,
      totalEpisodes: 26,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "In the year 2015, the Angels, huge, tremendously powerful, alien war machines, appear in Tokyo for the second time. The only hope for Mankind's survival lies in the Evangelion, a humanoid fighting machine developed by NERV, a special United Nations agency. Capable of withstanding anything the Angels can dish out, the Evangelion's one drawback lies in the limited number of people able to pilot them. Only a handful of teenagers, all born fourteen years ago, nine months after the Angels first appeared, are able to interface with the Evangelion. One such teenager is Shinji Ikari, whose father heads the NERV team that developed and maintains the Evangelion. Thrust into a maelstrom of battle and events that he does not understand, Shinji is forced to plumb the depths of his own inner resources for the courage and strength to not only fight, but to survive, or risk losing everything. <br><br>\n(Source: AniDB)<br>\n<br>\n <i>Note: Later releases include edited versions of Episodes 21-24 called the \"Director's Cut\" with some visual editing and adding extra scenes that appeared in the theatrical recap 'Death'.</i>",
      genres: [
        "Action",
        "Drama",
        "Mecha",
        "Mystery",
        "Psychological",
        "Sci-Fi",
      ],
      rating: 83,
      color: "#e4865d",
      type: "TV",
      releaseDate: 1995,
    },
    {
      id: "20464",
      malId: 20583,
      title: {
        romaji: "Haikyuu!!",
        english: "HAIKYU!!",
        native: "ハイキュー!!",
        userPreferred: "Haikyuu!!",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20464-eW7ZDBOcn74a.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20464-PpYjO9cPN1gs.jpg",
      coverHash: "hash",
      popularity: 435944,
      totalEpisodes: 25,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        'Inspired after watching a volleyball ace nicknamed "Little Giant" in action, small-statured Shouyou Hinata revives the volleyball club at his middle school. The newly-formed team even makes it to a tournament; however, their first match turns out to be their last when they are brutally squashed by the "King of the Court," Tobio Kageyama. Hinata vows to surpass Kageyama, and so after graduating from middle school, he joins Karasuno High School\'s volleyball team—only to find that his sworn rival, Kageyama, is now his teammate.\n<br><br>\nThanks to his short height, Hinata struggles to find his role on the team, even with his superior jumping power. Surprisingly, Kageyama has his own problems that only Hinata can help with, and learning to work together appears to be the only way for the team to be successful. Based on Haruichi Furudate\'s popular shounen manga of the same name, Haikyuu!! is an exhilarating and emotional sports comedy following two determined athletes as they attempt to patch a heated rivalry in order to make their high school volleyball team the best in Japan.\n<br><br>\n[Written by MAL Rewrite]',
      genres: ["Comedy", "Drama", "Sports"],
      rating: 83,
      color: "#e48635",
      type: "TV",
      releaseDate: 2014,
    },
    {
      id: "21827",
      malId: 33352,
      title: {
        romaji: "Violet Evergarden",
        english: "Violet Evergarden",
        native: "ヴァイオレット・エヴァーガーデン",
        userPreferred: "Violet Evergarden",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx21827-10F6m50H4GJK.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21827-ROucgYiiiSpR.jpg",
      coverHash: "hash",
      popularity: 393924,
      totalEpisodes: 13,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "A certain point in time, in the continent of Telesis. The great war which divided the continent into North and South has ended after four years, and the people are welcoming a new generation. Violet Evergarden, a young girl formerly known as “the weapon”, has left the battlefield to start a new life at CH Postal Service. There, she is deeply moved by the work of “Auto Memories Dolls”, who carry people's thoughts and convert them into words. Violet begins her journey as an Auto Memories Doll, and comes face to face with various people's emotions and differing shapes of love. There are words Violet heard on the battlefield, which she cannot forget. These words were given to her by someone she holds dear, more than anyone else. She does not yet know their meaning but she searches to find it.<br>\n<br>\n(Source: Anime News Network)",
      genres: ["Drama", "Fantasy", "Slice of Life"],
      rating: 85,
      color: "#3586e4",
      type: "TV",
      releaseDate: 2018,
    },
    {
      id: "20",
      malId: 20,
      title: {
        romaji: "NARUTO",
        english: "Naruto",
        native: "NARUTO -ナルト-",
        userPreferred: "NARUTO",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20-YJvLbgJQPCoI.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20-HHxhPj5JD13a.jpg",
      coverHash: "hash",
      popularity: 518512,
      totalEpisodes: 220,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Naruto Uzumaki, a hyperactive and knuckle-headed ninja, lives in Konohagakure, the Hidden Leaf village. Moments prior to his birth, a huge demon known as the Kyuubi, the Nine-tailed Fox, attacked Konohagakure and wreaked havoc. In order to put an end to the Kyuubi's rampage, the leader of the village, the 4th Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto. <br><br>\nShunned because of the presence of the Kyuubi inside him, Naruto struggles to find his place in the village. He strives to become the Hokage of Konohagakure, and he meets many friends and foes along the way. <br><br>\n(Source: MAL Rewrite)",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Supernatural",
      ],
      rating: 79,
      color: "#e47850",
      type: "TV",
      releaseDate: 2002,
    },
    {
      id: "101348",
      malId: 37521,
      title: {
        romaji: "VINLAND SAGA",
        english: "Vinland Saga",
        native: "ヴィンランド・サガ",
        userPreferred: "VINLAND SAGA",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101348-msJS8z91mG0P.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101348-pivKKffCAwAY.jpg",
      coverHash: "hash",
      popularity: 346240,
      totalEpisodes: 24,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Thorfinn is son to one of the Vikings' greatest warriors, but when his father is killed in battle by the mercenary leader Askeladd, he swears to have his revenge. Thorfinn joins Askeladd's band in order to challenge him to a duel, and ends up caught in the middle of a war for the crown of England.\n<br><br>\n(Source: Kodansha USA)",
      genres: ["Action", "Adventure", "Drama"],
      rating: 87,
      color: "#e45d50",
      type: "TV",
      releaseDate: 2019,
    },
    {
      id: "21507",
      malId: 32182,
      title: {
        romaji: "Mob Psycho 100",
        english: "Mob Psycho 100",
        native: "モブサイコ100",
        userPreferred: "Mob Psycho 100",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21507-BICFCVZY3xQb.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21507-Qx8bGsLXUgLo.jpg",
      coverHash: "hash",
      popularity: 444297,
      totalEpisodes: 12,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        'The story revolves around "Mob," a boy who will explode if his emotional capacity reaches 100%. This boy with psychic powers earned his nickname "Mob" because he does not stand out among other people. He keeps his psychic powers bottled up so he can live normally, but if his emotional level reaches 100, something will overwhelm his entire body.<br>\n<br>\n(Source: Anime News Network)',
      genres: [
        "Action",
        "Comedy",
        "Drama",
        "Psychological",
        "Slice of Life",
        "Supernatural",
      ],
      rating: 84,
      color: "#d65d1a",
      type: "TV",
      releaseDate: 2016,
    },
    {
      id: "20665",
      malId: 23273,
      title: {
        romaji: "Shigatsu wa Kimi no Uso",
        english: "Your lie in April",
        native: "四月は君の嘘",
        userPreferred: "Shigatsu wa Kimi no Uso",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20665-CnzR2zVpdxtR.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20665-j4kSsfhfkM24.jpg",
      coverHash: "hash",
      popularity: 446828,
      totalEpisodes: 22,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Piano prodigy Arima Kousei dominated the competition and all child musicians knew his name. But after his mother, who was also his instructor, passed away, he had a mental breakdown while performing at a recital. This resulted in him no longer being able to hear the sound of his piano playing. Two years later, Kousei hasn’t touched the piano and views the world without any flair or color. He was content at living out his life with his good friends Tsubaki and Watari until, one day, a girl changed everything. Miyazono Kaori is a pretty, free spirited violinist whose playing style reflects her personality. Kaori helps Kousei return to the music world and show that it should be free and mold breaking unlike the structured and rigid style Kousei was used to.",
      genres: ["Drama", "Music", "Romance", "Slice of Life"],
      rating: 84,
      color: "#e4bb50",
      type: "TV",
      releaseDate: 2014,
    },
    {
      id: "21087",
      malId: 30276,
      title: {
        romaji: "One Punch Man",
        english: "One-Punch Man",
        native: "ワンパンマン",
        userPreferred: "One Punch Man",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21087-UV2tu6exrfXz.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21087-sHb9zUZFsHe1.jpg",
      coverHash: "hash",
      popularity: 564495,
      totalEpisodes: 12,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Saitama has a rather peculiar hobby, being a superhero, but despite his heroic deeds and superhuman abilities, a shadow looms over his life. He's become much too powerful, to the point that every opponent ends up defeated with a single punch.\n<br><br>\nThe lack of challenge has driven him into a state of apathy, as he watches his life pass by having lost all enthusiasm, at least until he's unwillingly thrust in the role of being a mentor to the young and revenge-driven Genos.   \n\n",
      genres: ["Action", "Comedy", "Sci-Fi", "Supernatural"],
      rating: 83,
      color: "#e4ae5d",
      type: "TV",
      releaseDate: 2015,
    },
    {
      id: "127230",
      malId: 44511,
      title: {
        romaji: "Chainsaw Man",
        english: "Chainsaw Man",
        native: "チェンソーマン",
        userPreferred: "Chainsaw Man",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx127230-FlochcFsyoF4.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/127230-o8IRwCGVr9KW.jpg",
      coverHash: "hash",
      popularity: 357078,
      totalEpisodes: 12,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        'Denji is a teenage boy living with a Chainsaw Devil named Pochita. Due to the debt his father left behind, he has been living a rock-bottom life while repaying his debt by harvesting devil corpses with Pochita.<br><br>\nOne day, Denji is betrayed and killed. As his consciousness fades, he makes a contract with Pochita and gets revived as "Chainsaw Man" — a man with a devil\'s heart.<br>\n<br>\n(Source: Crunchyroll)',
      genres: ["Action", "Drama", "Horror", "Supernatural"],
      rating: 85,
      color: "#6b1a1a",
      type: "TV",
      releaseDate: 2022,
    },
  ],
};
