export const demoWinter = {
  currentPage: 1,
  hasNextPage: true,
  totalPages: 1000,
  totalResults: 5000,
  results: [
    {
      id: "101759",
      malId: 37779,
      title: {
        romaji: "Yakusoku no Neverland",
        english: "The Promised Neverland",
        native: "約束のネバーランド",
        userPreferred: "Yakusoku no Neverland",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101759-NhSwxv7HY9y9.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101759-MhlCoeqnODso.jpg",
      coverHash: "hash",
      popularity: 483819,
      totalEpisodes: 12,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Emma, Norman and Ray are the brightest kids at the Grace Field House orphanage. And under the care of the woman they refer to as “Mom,” all the kids have enjoyed a comfortable life. Good food, clean clothes and the perfect environment to learn—what more could an orphan ask for? One day, though, Emma and Norman uncover the dark truth of the outside world they are forbidden from seeing.\n<br><br>\n(Source: Viz Media)",
      genres: [
        "Drama",
        "Fantasy",
        "Horror",
        "Mystery",
        "Psychological",
        "Thriller",
      ],
      rating: 84,
      color: "#e4ae50",
      type: "TV",
      releaseDate: 2019,
    },
    {
      id: "20755",
      malId: 24833,
      title: {
        romaji: "Ansatsu Kyoushitsu",
        english: "Assassination Classroom",
        native: "暗殺教室",
        userPreferred: "Ansatsu Kyoushitsu",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20755-q0b3Ok1cAbPd.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20755-D4ipww9U8YkC.jpg",
      coverHash: "hash",
      popularity: 465066,
      totalEpisodes: 22,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "The students of class 3-E have a mission: kill their teacher before graduation. He has already destroyed the moon, and has promised to destroy the Earth if he can not be killed within a year. But how can this class of misfits kill a tentacled monster, capable of reaching Mach 20 speed, who may be the best teacher any of them have ever had?",
      genres: ["Action", "Comedy", "Drama", "Supernatural"],
      rating: 79,
      color: "#e4d650",
      type: "TV",
      releaseDate: 2015,
    },
    {
      id: "110277",
      malId: 40028,
      title: {
        romaji: "Shingeki no Kyojin: The Final Season",
        english: "Attack on Titan Final Season",
        native: "進撃の巨人 The Final Season",
        userPreferred: "Shingeki no Kyojin: The Final Season",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx110277-qDRIhu50PXzz.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/110277-iuGn6F5bK1U1.jpg",
      coverHash: "hash",
      popularity: 459577,
      totalEpisodes: 16,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "It’s been four years since the Scout Regiment reached the shoreline, and the world looks different now. Things are heating up as the fate of the Scout Regiment—and the people of Paradis—are determined at last. However, Eren is missing. Will he reappear before age-old tensions between Marleyans and Eldians result in the war of all wars?<br>\n<br>\n(Source: Crunchyroll)",
      genres: ["Action", "Drama", "Fantasy", "Mystery"],
      rating: 86,
      color: "#ae5d1a",
      type: "TV",
      releaseDate: 2021,
    },
    {
      id: "21234",
      malId: 31043,
      title: {
        romaji: "Boku dake ga Inai Machi",
        english: "ERASED",
        native: "僕だけがいない街",
        userPreferred: "Boku dake ga Inai Machi",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx21234-v2NMgPyoVRoM.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21234-7lfSSPoMmwr2.jpg",
      coverHash: "hash",
      popularity: 446750,
      totalEpisodes: 12,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Satoru Fujinuma is a 29 year old manga artist struggling to make a name for himself following his debut. But, that was not the only thing in his life that Satoru was feeling frustrated about… He has a unique supernatural ability of being forced to prevent deaths and catastrophes by being sent back in time before the incident occurred, repeating time until the accident is prevented. One day, he gets involved in an accident that has him framed as a murderer. Desperate to save the victim, he sends himself back in time only to find himself as a grade-schooler one month before fellow classmate Kayo Hinazuki went missing. Satoru now embarks on a new quest: to save Kayo and solve the mystery behind her disappearance.\n",
      genres: ["Drama", "Mystery", "Psychological", "Supernatural", "Thriller"],
      rating: 81,
      color: "#e4a150",
      type: "TV",
      releaseDate: 2016,
    },
    {
      id: "1735",
      malId: 1735,
      title: {
        romaji: "NARUTO: Shippuuden",
        english: "Naruto: Shippuden",
        native: "NARUTO -ナルト- 疾風伝",
        userPreferred: "NARUTO: Shippuuden",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1735-Az5gbEdWeotG.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1735.jpg",
      coverHash: "hash",
      popularity: 442065,
      totalEpisodes: 500,
      currentEpisode: null,
      countryOfOrigin: "JP",
      description:
        "Naruto: Shippuuden is the continuation of the original animated TV series Naruto. The story revolves around an older and slightly more matured Uzumaki Naruto and his quest to save his friend Uchiha Sasuke from the grips of the snake-like Shinobi, Orochimaru. After 2 and a half years Naruto finally returns to his village of Konoha, and sets about putting his ambitions to work, though it will not be easy, as he has amassed a few (more dangerous) enemies, in the likes of the shinobi organization; Akatsuki. <br><br>\n(Source: Anime News Network)",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Supernatural",
      ],
      rating: 81,
      color: "#e4865d",
      type: "TV",
      releaseDate: 2007,
    },
  ],
};
